# import standard word embeddings, w

In [25]:
import numpy as np
import math
import re
import string

In [22]:
contractions_dict = {
"ain't": "am not",
"aren't": "are not",
"can't": "cannot",
"can't've": "cannot have",
"'cause": "because",
"could've": "could have",
"couldn't": "could not",
"couldn't've": "could not have",
"didn't": "did not",
"doesn't": "does not",
"don't": "do not",
"hadn't": "had not",
"hadn't've": "had not have",
"hasn't": "has not",
"haven't": "have not",
"he'd": "he had",
"he'd've": "he would have",
"he'll": "he shall",
"he'll've": "he shall have",
"he's": "he has",
"how'd": "how did",
"how'd'y": "how do you",
"how'll": "how will",
"how's": "how is",
"I'd": "I would",
"I'd've": "I would have",
"I'll": "I shall",
"I'll've": "I shall have",
"I'm": "I am",
"I've": "I have",
"isn't": "is not",
"it'd": "it would",
"it'd've": "it would have",
"it'll": "it will",
"it'll've": "it will have",
"it's": "it is",
"let's": "let us",
"ma'am": "madam",
"mayn't": "may not",
"might've": "might have",
"mightn't": "might not",
"mightn't've": "might not have",
"must've": "must have",
"mustn't": "must not",
"mustn't've": "must not have",
"needn't": "need not",
"needn't've": "need not have",
"o'clock": "of the clock",
"oughtn't": "ought not",
"oughtn't've": "ought not have",
"shan't": "shall not",
"sha'n't": "shall not",
"shan't've": "shall not have",
"she'd": "she would",
"she'd've": "she would have",
"she'll": "she will",
"she'll've": "she will have",
"she's": "she is",
"should've": "should have",
"shouldn't": "should not",
"shouldn't've": "should not have",
"so've": "so have",
"so's": "so is",
"that'd": "that would",
"that'd've": "that would have",
"that's": "that is",
"there'd": "there would",
"there'd've": "there would have",
"there's": "there is",
"they'd": "they would",
"they'd've": "they would have",
"they'll": "they will",
"they'll've": "they will have",
"they're": "they are",
"they've": "they have",
"to've": "to have",
"wasn't": "was not",
"we'd": "we would",
"we'd've": "we would have",
"we'll": "we will",
"we'll've": "we will have",
"we're": "we are",
"we've": "we have",
"weren't": "were not",
"what'll": "what will",
"what'll've": "what will have",
"what're": "what are",
"what's": "what is",
"what've": "what have",
"when's": "when is",
"when've": "when have",
"where'd": "where did",
"where's": "where is",
"where've": "where have",
"who'll": "who will",
"who'll've": "who will have",
"who's": "who is",
"who've": "who have",
"why's": "why is",
"why've": "why have",
"will've": "will have",
"won't": "will not",
"won't've": "will not have",
"would've": "would have",
"wouldn't": "would not",
"wouldn't've": "would not have",
"y'all": "you all",
"y'all'd": "you all would",
"y'all'd've": "you all would have",
"y'all're": "you all are",
"y'all've": "you all have",
"you'd": "you would",
"you'd've": "you would have",
"you'll": "you will",
"you'll've": "you will have",
"you're": "you are",
"you've": "you have"
}

In [2]:
embeddings_dict = {}
with open("glove.6B.50d.txt", 'r', encoding="utf-8") as f:
    for line in f:
        values = line.split()
        word = values[0]
        vector = np.asarray(values[1:], "float32")
        embeddings_dict[word] = vector

In [3]:
len(embeddings_dict)

400000

In [6]:
embeddings_dict['fun']

array([-0.23764 ,  0.43119 , -0.72154 , -0.15513 ,  0.26631 , -0.4445  ,
       -0.4452  , -0.66205 , -0.35055 ,  1.0197  , -0.91729 ,  0.20477 ,
       -0.44747 ,  0.071965,  0.82335 , -0.023837,  0.76155 ,  0.9766  ,
       -0.44837 , -0.7963  ,  0.027471,  1.0583  ,  0.41688 ,  0.73721 ,
        1.1753  , -0.84602 , -1.1009  ,  0.68862 ,  1.2378  , -0.98452 ,
        2.3631  ,  1.0793  , -0.15267 ,  0.13733 , -0.28105 ,  0.37881 ,
       -0.15635 ,  0.47079 , -0.47013 , -0.53729 ,  0.20005 ,  0.16393 ,
       -0.53282 ,  0.63922 ,  0.44527 , -0.10678 ,  0.44169 , -0.47774 ,
        0.37379 ,  1.0782  ], dtype=float32)

In [7]:
len(embeddings_dict['fun'])

50

In [8]:
W = np.zeros((len(embeddings_dict), len(embeddings_dict['fun'])), dtype = 'float32')

In [9]:
word_map = {}
for index,word in enumerate(embeddings_dict.keys()):
    word_map[word] = index
    W[index] = embeddings_dict[word]

Randomly initialize M and calculate E

In [10]:
len(W[0])

50

In [11]:
k = len(W[0]) # Standard vector dimensions
d = 25 # Required dimensions
M = np.random.rand(k,d)

In [12]:
def sigmoid(x):
    return 1/(1+math.exp(-x))
vec_sigmoid = np.vectorize(sigmoid)

In [13]:
E = vec_sigmoid(np.matmul(W,M))

In [14]:
E.shape

(400000, 25)

# 3.2 Alignment loss in word space
Selection of pivot and domain specific words

Firstly,the candidate pool of pivot words is pinned to a set of common words that appear in more than theta_c documents in each domain.

In [15]:
# reading the document
# for each word in the document calculate its positive frequency and negative frequency.
# first build a vocabulary of words

# read the source document
# make the vocabulary of the document

In [16]:
import pandas as pd

In [17]:
src_df = pd.read_csv('books_labelled.txt', header = None, sep ='\t')

In [18]:
sentences = src_df.values[:,0]
labels = src_df.values[:,1]

In [23]:
contractions_re = re.compile('(%s)' % '|'.join(contractions_dict.keys()))
def expand_contractions(s, contractions_dict=contractions_dict):
     def replace(match):
         return contractions_dict[match.group(0)]
     return contractions_re.sub(replace, s)

In [26]:
translator = str.maketrans(string.punctuation, ' '*len(string.punctuation))
for i in range(len(sentences)):
    sentences[i] = expand_contractions(sentences[i]).lower().translate(translator)

In [33]:
vocab = set()
for sentence in sentences:
    for word in sentence.split(' '):
        vocab.add(word)
vocab.remove('')

In [35]:
src_word_map = {}
for index,word in enumerate(vocab):
    src_word_map[word] = index

In [36]:
src_word_freq = np.zeros((len(vocab),2))

In [39]:
for sentence,label in zip(sentences,labels):
    for word in sentence.split(' '):
        if(word != ''):
            src_word_freq[src_word_map[word],label] += 1

In [40]:
candidate_pool = set()
theta_c = 5
for word in vocab:
    positive_instances = src_word_freq[src_word_map[word],1]
    negative_instances = src_word_freq[src_word_map[word],0]
    if(positive_instances >= theta_c and negative_instances >= theta_c):
        candidate_pool.add(word)

In [41]:
len(vocab)

1857

In [42]:
len(candidate_pool)

175

In [44]:
def get_entropy(a,b):
    total = a+b
    sum1 = math.log(a/(a+b))
    sum1 += math.log(b/(a+b))
    return -sum1

In [45]:
cw_entropy = {}
for word in candidate_pool:
    positive_instances = src_word_freq[src_word_map[word],1]
    negative_instances = src_word_freq[src_word_map[word],0]
    entropy = get_entropy(positive_instances, negative_instances)
    cw_entropy[word] = entropy

In [46]:
pivot_words = set()
non_pivot = set()
theta_b = 1.45
for word in candidate_pool:
    if(cw_entropy[word] > theta_b):
        pivot_words.add(word)
    else:
        non_pivot.add(word)

In [47]:
len(pivot_words)

67

In [51]:
len(non_pivot)

108

In [52]:
# for each pivot word select k non-pivot words that co-occur the most with it
pivot_map = {}
non_pivot_map = {}
for index,word in enumerate(pivot_words):
    pivot_map[word] = index
    
for index,word in enumerate(non_pivot):
    non_pivot_map[word] = index

In [53]:
pivot_co_freq = np.zeros((len(pivot_words), len(non_pivot)), dtype = np.int32)

In [54]:
for sentence in sentences:
    sent_pivot = set()
    sent_non_pivot = set()
    for word in sentence.split(' '):
        if(word in pivot_words):
            sent_pivot.add(word)
        elif(word in non_pivot):
            sent_non_pivot.add(word)
    
    for word in sent_pivot:
        for word2 in sent_non_pivot:
            pivot_co_freq[pivot_map[word], non_pivot_map[word2]] += 1

In [55]:
non_pivot_rv_map = {}
for word in non_pivot_map.keys():
    non_pivot_rv_map[non_pivot_map[word]] = word

In [56]:
# for each pivot word get k non pivot words
k = 5
domain_specific_words = set()
pivot_cor_k_words = {}
for word in pivot_words:
    indices = pivot_co_freq[pivot_map[word],:].ravel().argsort()[-k:]
    pivot_cor_k_words[word] = [non_pivot_rv_map[index] for index in indices]
    for word2 in [non_pivot_rv_map[index] for index in indices]:
        domain_specific_words.add(word2)

In [57]:
domain_specific_map = {}
for index,word in enumerate(domain_specific_words):
    domain_specific_map[word] = index

In [58]:
pivot_cor_k_words

{'cell': ['and', 'my', 'the', 'phone', 'i'],
 'do': ['and', 'it', 'to', 'the', 'i'],
 'while': ['and', 'is', 'a', 'the', 'it'],
 'these': ['of', 'to', 'the', 'and', 'i'],
 'make': ['this', 'and', 'to', 'the', 'i'],
 'there': ['it', 'i', 'is', 'the', 'a'],
 'very': ['with', 'i', 'is', 'and', 'the'],
 'good': ['i', 'it', 'a', 'and', 'the'],
 'few': ['but', 'have', 'the', 'i', 'a'],
 'not': ['this', 'and', 'it', 'the', 'i'],
 'be': ['this', 'and', 'to', 'the', 'i'],
 'enough': ['for', 'to', 'it', 'i', 'the'],
 'did': ['this', 'that', 'it', 'i', 'the'],
 'great': ['it', 'is', 'a', 'the', 'and'],
 'quality': ['i', 'it', 'is', 'and', 'the'],
 'camera': ['phone', 'and', 'is', 'the', 'a'],
 'thing': ['was', 'that', 'it', 'i', 'the'],
 'get': ['my', 'and', 'to', 'the', 'i'],
 'only': ['but', 'a', 'i', 'it', 'the'],
 'cheap': ['low', 'is', 'it', 'as', 'the'],
 'comfortable': ['ear', 'and', 'is', 'the', 'it'],
 'you': ['for', 'is', 'a', 'to', 'the'],
 'problem': ['it', 'had', 'the', 'with', 'i'],

In [59]:
f = len(domain_specific_words)

In [60]:
f

28

# 3.2.2 Pivot polarity graph

In [61]:
src_bag_of_words = np.zeros((len(sentences), len(vocab)), dtype = np.int32)

In [63]:
for index,sentence in enumerate(sentences):
    for word in sentence.split(' '):
        if(word != ''):
            src_bag_of_words[index, src_word_map[word]] += 1

In [64]:
from sklearn.linear_model import LinearRegression

In [65]:
lr_model = LinearRegression()
lr_model.fit(src_bag_of_words, labels)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [66]:
lr_model.coef_

array([ 3.12187135e-01, -6.72938481e+10, -5.36313533e-02, ...,
        9.85351037e+09,  2.26951558e+09,  4.86286584e+10])

In [67]:
def polarity(a):
    if(a>0):
        return 1
    elif(a<0):
        return -1
    else:
        return 0

In [68]:
pivot_polarity = {}
for word in pivot_words:
    aI = lr_model.coef_[src_word_map[word]]
    pivot_polarity[word] = polarity(aI)

In [69]:
size = len(pivot_words)+f
R_matrix = np.zeros((size,size), dtype = np.int32)

In [70]:
for word in pivot_words:
    for word2 in pivot_words:
        R_matrix[pivot_map[word], pivot_map[word2]] = max(
            [0,pivot_polarity[word]*pivot_polarity[word2]]
        )

In [71]:
R_matrix

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [72]:
g = len(pivot_words)
for pivot in pivot_words:
    pivot_index = pivot_map[pivot]
    for word in pivot_cor_k_words[pivot]:
        non_pivot_index = g+domain_specific_map[word]
        R_matrix[pivot_index, non_pivot_index] = 1
        R_matrix[non_pivot_index, pivot_index] = 1

In [73]:
R_matrix

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [117]:
# Calculate the p-matrix
K_preplex = 50
sigma_i = math.log(K_preplex)/math.log(2)

In [118]:
total_words = pivot_words.union(domain_specific_words)

In [119]:
dist_matrix = np.zeros((len(total_words),len(total_words)))

In [120]:
def get_index(word):
    if word in pivot_words:
        index = pivot_map[word]
        return index
    else:
        index = g+domain_specific_map[word]
        return index

In [121]:
def get_exp_distance(word1, word2):
    w1_vec = embeddings_dict[word1]
    w2_vec = embeddings_dict[word2]
    dist = np.linalg.norm((w1_vec-w2_vec),ord=2)**2
    dist = math.exp(-dist/sigma_i)
    return dist

In [122]:
for word1 in total_words:
    for word2 in total_words:
        w1 = get_index(word1)
        w2 = get_index(word2)
        dist_matrix[w1,w2] = get_exp_distance(word1,word2)

In [123]:
P_matrix = np.zeros((g+f,g+f))

In [124]:
np.sum(dist_matrix[0])-1

0.48770855812463654

In [125]:
for i in range(g+f):
    for j in range(g+f):
        P_matrix[i,j] = dist_matrix[i,j]/(np.sum(dist_matrix[i]) - 1)

In [126]:
alpha = 0.5
R_mod = alpha*R_matrix+(1-alpha)*P_matrix

In [127]:
R_mod

array([[1.52520243e+00, 5.00791538e-01, 5.10646647e-01, ...,
        2.23817105e-03, 4.00792677e-03, 4.24550749e-03],
       [5.00056291e-01, 5.72907724e-01, 5.02048249e-01, ...,
        2.39489434e-04, 2.36890737e-04, 4.85421816e-03],
       [5.00363180e-01, 5.00982488e-01, 5.34971815e-01, ...,
        6.69210744e-03, 2.89163679e-03, 7.30898069e-03],
       ...,
       [1.84688345e-04, 2.77887273e-04, 1.61882752e-02, ...,
        8.45971714e-02, 1.09727475e-03, 2.64497997e-03],
       [8.08138498e-04, 6.71661080e-04, 1.70923281e-02, ...,
        2.68123692e-03, 2.06716739e-01, 3.46136952e-03],
       [1.92324094e-04, 3.09214221e-03, 9.70626975e-03, ...,
        1.45204560e-03, 7.77653319e-04, 4.64422990e-02]])

In [128]:
np.matmul(embeddings_dict['word'],M)

array([-0.25961138,  1.48567906, -1.32466438, -0.87788263,  0.41942744,
        1.86352817,  0.22411983, -0.13237484,  2.73876428,  1.07093671,
        0.15576551,  0.60441445,  1.84034467,  1.68411009, -0.34509863,
       -1.6438546 ,  1.79851692,  3.57073491, -0.21463936, -0.46626625,
        0.40386841, -0.235728  , -0.64457899, -0.77657504, -0.94604055])

In [129]:
def get_E_exp_distance(word1, word2, M):
    w1_vec = np.matmul(embeddings_dict[word1],M)
    w2_vec = np.matmul(embeddings_dict[word2],M)
    dist = np.linalg.norm((w1_vec-w2_vec),ord=2)**2
    dist = math.exp(-dist/sigma_i)
    return dist

In [130]:
dist_E_matrix = np.zeros((len(total_words),len(total_words)))
for word1 in total_words:
    for word2 in total_words:
        w1 = get_index(word1)
        w2 = get_index(word2)
        dist_E_matrix[w1,w2] = get_E_exp_distance(word1,word2,M)

In [131]:
np.min(dist_E_matrix)

8.336159359816297e-143

In [132]:
Q_matrix = np.zeros((g+f,g+f))
for i in range(g+f):
    for j in range(g+f):
        Q_matrix[i,j] = dist_E_matrix[i,j]/(np.sum(dist_E_matrix[i]) - 1)

In [133]:
Q_matrix

array([[2.77636851e+01, 4.75136977e-17, 1.15897291e-33, ...,
        1.02925889e-89, 2.57043821e-03, 1.14105493e-40],
       [3.35798650e-18, 1.96217268e+00, 1.61506097e-06, ...,
        8.23822227e-36, 9.28586643e-14, 2.98740395e-08],
       [2.56319769e-35, 5.05402774e-07, 6.14024819e-01, ...,
        3.35538006e-15, 3.23110183e-25, 1.07679647e-02],
       ...,
       [1.39194662e-89, 1.57641785e-34, 2.05178031e-13, ...,
        3.75469845e+01, 5.61867838e-72, 6.18145025e-11],
       [3.99314682e-03, 2.04112887e-12, 2.26960322e-23, ...,
        6.45422839e-72, 4.31305722e+01, 9.68554515e-31],
       [7.67390513e-42, 2.84278301e-08, 3.27442227e-02, ...,
        3.07398895e-12, 4.19300940e-32, 1.86718344e+00]])

# 3.3 Neighbor loss in document space